// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TennisAngular10.Models;

namespace TennisAngular10.Migrations
{
    [DbContext(typeof(TennisDBContext))]
    [Migration("20211205180000_Ranking_F_2021")]
    partial class Ranking_F_2021
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
