version: '3.1'

services:
  tennis-postgres-db:
    image: postgres:11.1
    ports:
      - "4001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - tennisplayers_network
    restart: on-failure:3

  tennis-postgres-webapi-csharp:
    ##image: tennisplayers-java
    build:
      context: ./TennisPostgresWebApiCSharp
    environment:
      - ConnectionStrings__DefaultConnection=Server=tennis-postgres-db;Port=5432;Database=postgres;User Id=postgres;Password=;
      #- ASPNETCORE_URLS=https://+;http://+;
    ports:
      - "53316:80"
    depends_on:
      - tennis-postgres-db
#    networks:
#      - tennisplayers_network
    restart: on-failure:3

  tennis-vue:
    build:
      context: ./vuejs
    ports:
      - "8080:80"
    environment:
      VUE_APP_WEBAPI_URL: ${VUE_APP_WEBAPI_URL}
    depends_on:
      - tennis-postgres-webapi-csharp

  tennis-angular:
    build:
      context: ./Angular
    ports:
      - "4200:80"
    environment:
      VUE_APP_WEBAPI_URL: ${VUE_APP_WEBAPI_URL}
    depends_on:
      - tennis-postgres-webapi-csharp
  

volumes:
  postgres-data:
    driver: local
    
#networks:
#  tennisplayers_network:
#    external: true
