version: '3.1'

services:
  tennisplayers-db:
    image: postgres:11.1
    ports:
      - "4001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - tennisplayers_network
    restart: on-failure:3

  tennisplayers-dotnet-core-webapi:
    ##image: tennisplayers-java
    build:
      context: ./TennisAngular10
    environment:
      - ConnectionStrings:DefaultConnection__Server=tennisplayers-db;Port=5432;Database=postgres;User Id=postgres;Password=;
      #- ASPNETCORE_URLS=https://+;http://+;
    ports:
      - "53316:80"
    depends_on:
      - tennisplayers-db
#    networks:
#      - tennisplayers_network
    restart: on-failure:3

  tennisplayers-vue:
    build:
      context: ./vuejs
    ports:
      - "8080:80"
    environment:
      VUE_APP_WEBAPI_URL: ${VUE_APP_WEBAPI_URL}
    depends_on:
      - tennisplayers-dotnet-core-webapi

  tennisplayers-angular:
    build:
      context: ./Angular
    ports:
      - "4200:80"
    environment:
      VUE_APP_WEBAPI_URL: ${VUE_APP_WEBAPI_URL}
    depends_on:
      - tennisplayers-dotnet-core-webapi
  

volumes:
  postgres-data:
    driver: local
    
#networks:
#  tennisplayers_network:
#    external: true
