version: '3.1'

services:
  tennis-postgres-db:
    image: postgres:11.1
    ports:
      - "4001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure:3

  tennis-postgres-graphql-csharp:
    build:
      context: ./TennisPostgresGraphQLCSharp
    environment:
      - ConnectionStrings__DefaultConnection=Server=tennis-postgres-db;Port=5432;Database=postgres;User Id=postgres;Password=;
    ports:
      - "52264:80"
    depends_on:
      - tennis-postgres-db
    restart: on-failure:3

volumes:
  postgres-data:
    driver: local
