version: '3.1'

services:
  tennisplayers-db:
    image: postgres:11.1
    ports:
      - "4001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - beta-private_beta_network
    restart: on-failure:3

##  tennisplayers-java:
##    image: tennisplayers-java
##    ports:
##      - "8220:8220"
##    depends_on:
##      - tennisplayers-db
#    networks:
#      - beta-private_beta_network
##    restart: on-failure:3

volumes:
  postgres-data:
    driver: local
    
#networks:
#  beta-private_beta_network:
#    external: true
