version: '3.1'

services:
  tennis-mongo-db:
    build:
      context: ./mongo-db
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: on-failure:3

  tennis-mongo-webapi-csharp:
    build:
      context: ./TennisMongoDBWebApiCSharp
    environment:
      - TennisDatabaseSettings__ConnectionString=mongodb://tennis_user:tennis_pass@tennis-mongo-db:27017/tennis_players
    ports:
      - "53316:80"
    depends_on:
      - tennis-mongo-db
    restart: on-failure:3

  tennis-vue:
    build:
      context: ./vuejs
    ports:
      - "8080:80"
    environment:
      VUE_APP_WEBAPI_URL: ${VUE_APP_WEBAPI_URL}
    depends_on:
      - tennis-mongo-webapi-csharp

  tennis-angular:
    build:
      context: ./Angular
    ports:
      - "4200:80"
    environment:
      VUE_APP_WEBAPI_URL: ${VUE_APP_WEBAPI_URL}
    depends_on:
      - tennis-mongo-webapi-csharp

  tennis-react:
    build:
      context: ./reactjs
    ports:
      - "3000:80"
    environment:
      VUE_APP_WEBAPI_URL: ${VUE_APP_WEBAPI_URL}
    depends_on:
      - tennis-mongo-webapi-csharp

  tennis-blazor:
    build:
      context: ./TennisMvcClient
    environment:
      - BasePath=http://tennis-mongo-webapi-csharp:80
      - Logging__LogLevel__Microsoft=Information
      - DetailedErrors=true
    ports:
      - "5000:80"
    depends_on:
      - tennis-mongo-webapi-csharp
  

volumes:
  mongodb-data:    
    driver: local
    
#networks:
#  tennisplayers_network:
#    external: true
