version: '3.1'

services:
  tennis-postgres-db:
    image: postgres:11.1
    ports:
      - "4001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure:3

volumes:
  postgres-data:
    driver: local
    
