version: '3.1'

services:
  tennis-mongo-db:
    image: mongo:3.6.21
    #command: mongod --serviceExecutor adaptive
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    restart: on-failure:3

##  tennisplayers-java:
##    image: tennisplayers-java
##    ports:
##      - "8220:8220"
##    depends_on:
##      - tennisplayers-db
#    networks:
#      - beta-private_beta_network
##    restart: on-failure:3

volumes:
  mongodb-data:    
    driver: local
    
#networks:
#  beta-private_beta_network:
#    external: true
